<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerKHuUhU6\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerKHuUhU6/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerKHuUhU6.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerKHuUhU6\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerKHuUhU6\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'KHuUhU6',
    'container.build_id' => 'ec489f3c',
    'container.build_time' => 1572337404,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerKHuUhU6');
