<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerEnlKo8a\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerEnlKo8a/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerEnlKo8a.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerEnlKo8a\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerEnlKo8a\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'EnlKo8a',
    'container.build_id' => '91b2c9a4',
    'container.build_time' => 1572334792,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerEnlKo8a');
